name = "glorage"
version = "1.0.0"
description = "Gleam thread local storage"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "glorage" }
gleam = ">= 1.4.1"

[dependencies]
carpenter = ">= 0.3.1"
gleam_erlang = ">= 0.25.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
cleam = ">= 1.5.1"
gleeunit = ">= 1.0.0 and < 2.0.0"
